# Generated by Django 3.2.5 on 2021-07-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='files')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('skills', models.TextField(null=True)),
                ('designation', models.TextField(null=True)),
                ('qualification', models.TextField(null=True)),
            ],
        ),
    ]
