# Generated by Django 3.2.5 on 2021-07-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210718_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='designation',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(null=True),
        ),
    ]
