# Generated by Django 3.2.5 on 2021-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_resume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='designation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
