# Generated by Django 3.2.5 on 2021-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210718_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='qualification',
            new_name='college',
        ),
        migrations.AddField(
            model_name='resume',
            name='degree',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(null=True),
        ),
    ]
