# Generated by Django 3.2.5 on 2021-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210718_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
