# Generated by Django 3.2.5 on 2021-07-26 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resume_is_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
