# Generated by Django 3.2.5 on 2021-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210811_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='college',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='designation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
